### ISSUE TITLE
Disagreement in Romanization

### ISSUE THREAD

**Issue by irontigran** [irontigran/sun-tzu_the-art-of-war_lionel-giles#17]
In translators-intro-1, Giles quotes the Shiji (Shih Chi) talking about certain famous generals. In particular, 咎犯, romanized as Kao-fan.

The problem is those characters romanize to Jiu-fan in pinyin, or Chiu-fan in Wade-Giles.

Possibilities:
- I transcribed the wrong character
- Giles picked the incorrect romanization
- There's some other explanation I'm not thinking of

**Comment by thewchan** [comment]
In Chinese many characters have more than one pronunciation (think present-tense "read" and past-tense "read" for an English analogy), this is one of those cases.  咎 can be pronounced as kao or chiu (in Wade-Giles, or in PinYin gao or jiu). Therefore I think you can just leave it.
