### ISSUE TITLE
Normalized Chinese characters

### ISSUE THREAD

**Issue by irontigran** [irontigran/sun-tzu_the-art-of-war_lionel-giles#4]
Consider this article on normalized characters: https://ctext.org/faq/normalization

In short - there are various characters with different unicode code points that nonetheless look very similar on screen. The linked dictionary handles this by converting all instances of some characters to a different character that looks the same.

I have not done this, but this issue should be revisited.

As an example, the character U+FA1B (福) appears in the chapter 7 endnotes. The linked dictionary normalizes that character to U+798F (福)

**Comment by thewchan** [comment]
I have not look through the code for all Chinese characters that can be normalized, but 福 is indeed a more archaic way of rendering/writing 福, and isn't generally used anymore except for artistic reasons.
