### ISSUE TITLE
Changes from tools

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#62]
1. Typogrify makes a number of changes and all appear to be correct, i.e. should be accepted.
2. Semanticate also makes changes, but only some of them should be accepted. It catches several abbreviations that are missing semantics, but is also incorrectly tags some characters as roman that aren't roman. You'll need to accept the abbreviations and revert the others.
3. There is an &c. (technically `&amp;c.`) in note-92 that should be "etc."

**Comment by irontigran** [comment]
Should be fixed [here](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/94a1a0499452d6186f00cd419fdd4d5feb879fc6) and [here](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/61582a259be6ee50fa7a619dddf6759450e75a4e)
