### ISSUE TITLE
Roman numbers

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#63]
There are a number of roman numerals that still have the period following them. For example, references in intro-1 to "Chapter V. § 19", later in the same file, "internal evidence of I. § 15", and so forth throughout (the book, not just that file). These should be removed (see [here](https://standardebooks.org/manual/1.1.1/8-typography#8.8.4.1) in the manual).

There are also lower-case roman numerals in a few places; in general we uppercase all roman numerals even if they're lowercase in the source. (I have _thousands_ of these in _Decline and Fall_.)

Also, some of the endnote references having unnecessary periods after decimal numbers, e.g. "_Shi Ching_ II. 3. VI. 3 and II. 5. 11. 3." in note 211. The periods after the 3 and 5 are unnecessary, same as for the roman numerals.

Also, in that particular note (211), I question the 11; the format of the first reference is "roman, decimal, roman, decimal", while the latter is "roman, decimal, decimal, decimal". Further, that 11 looks more like two small-cap i's (eyes) to me in the scans. I suspect that should be "II 5 II 3". You might want to look at that throughout; I've seen other small-cap I's in the source that are 1's (ones) in the text. (Now, if you want to argue that the second roman should be differentiated, either by being lowercase or small-caps, in this particular case I won't argue with you, but that will need approval from Alex.)

**Comment by irontigran** [comment]
Fixed the lower case roman numerals and trailing periods in [these](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/764386bb85e1f581a8d157bcb831121eacd6d221) [three](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/89ddd9e1ba41df3470b39458e0e6b1f909740b0b) [commits](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/78f53a3a8e30308204badc69a052caf47f70e520).

I agree with your point on the roman / decimal confusion. I changed the specific instance you caught - I'll do another once-over to catch any others.

I'll have to look at the built epub, but I'm inclined to let the second set of roman numerals stay uppercase.
