### ISSUE TITLE
Paragraph id's

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#64]
There are three paragraph id's in intro-1 that weren't changed to include the section id in front of them, i.e. two referring to p-21 in chapter 6, one p-30 in chapter-11.

Also, there is an id on paragraph 33 in that file; the prefix is intro-1, but the section id is introduction-1, so the id should be introduction-1-p-33. The same is true throughout; the id's should all be constructed with the section id as the prefix.
(Alex has updated the manual to include instructions on this, but I don't think they've been generated for the web yet.)

**Comment by irontigran** [comment]
Should be fixed [here](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/c4001bab597ee7ae584e1d65045664a9357ed983)
