### ISSUE TITLE
Filenames vs Id's

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#65]
Per [here](https://standardebooks.org/manual/1.1.1/5-general-xhtml-patterns#5.1.1.2) in the manual, the section id and filename should be identical. The intro's have filenames of "translators-intro-X", but ids of "introduction-X". The two should be the same.

**Comment by irontigran** [comment]
[Fixed](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/cd226f422a96af9a283e9927eba5c002c1ec9ba6)
