### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#66]
1. There's a cross-ref in intro-1 that says, "…briefly related in Chapter 5 § 19, note 292. In this particular case, the text being referred to is in the note, so the Chapter 5 § 19 is irrelevant; the text is in the note, so the link to note 292 is all that's needed. (Same for reference to note 225 in note 211; there are probably others.) Conversely, note 301 has a link for "note on V § 19.” but the text doesn't say which note it is. Since we're being directed to a note, the text should say what note instead of what chapter/paragraph.
2. There's a blockquote of French in the Translator's preface. It is marked with the appropriate tag, but there's no CSS to cause it to be italicized. (We italicize foreign language words/phrases/quotes/etc. regardless of whether it is in the source, just like we _don't_ italicize word that appear in M-W, even if they are italicized in the source.) See [here](https://standardebooks.org/manual/1.1.1/8-typography#8.2.8.6) in the manual for example CSS. That same paragraph has an italicized phrase at the beginning, so you'll need CSS to turn that back to normal text. I'm not crazy about the unsemanticated italics for that phrase, but it's not emphasis either; maybe `<q>` would be better, since it's quoting the phrase?
3. Endnote 65 says, "See the _end of the passage_ quoted… here" (emphasis mine), but the link is to the blockquote, i.e. the beginning of the passage. Shouldn't it link straight to the paragraph being referred to at the end of the passage?
4. In intro-1, the sentence starting "In the chapter entitles…" begins a new paragraph in both scans, but not in the file. Was that on purpose, or just a carryover from the transcription?
5. This is subjective, so you're free to ignore it. I found the table of dates in intro-1 to be crowded; I thought it was easier to read if there was a little padding between the text and the vertical bar. I put `padding-left: .25em;` in the existing `table td + td` CSS, then added a `table td` CSS with padding-right, and thought it looked a lot better. But, again, subjective, so not required.
6. You didn't center (horizontally) the dedication to match the source, was that intentional?
7. There are bracketed phrases in a few places; are those something other than normal asides? If not, the brackets should be changed to parentheses. (Some of them are editorial inserts into a quote; those can stay bracketed, but the others I'm not sure of.)
8. There are some verso/recto abbreviations that have extraneous trailing periods, e.g. notes 531 and 532.

**Comment by irontigran** [comment]
For the French blockquote - I understand the italicized phrase at the beginning to be a chapter title or some kind of heading. Google translate says "Skill in the government of the Troops", which has at least some vague relation to Sun Tzu's chapter title, so it's not hard for me to imagine that this is Amiot's translation of the chapter title.

Your assessment is that it's best to differentiate it from the rest of the quote by turning it back to normal text while the rest of the block is italicized? `<q>` doesn't seem appropriate to me here as it's just a part of the larger blockquote.

**Comment by irontigran** [comment]
For number 1- Giles says "Cf. _Tu Mu's_ note on V, &sect; 19". He does quote Tu Mu in his own note of course. I feel like replacing the phrase with "Cf. Tu Mu's note 292" falsely implies Tu Mu numbered his notes.

What if we try "Cf. Tu Mu's note quoted in note 292"?

**Comment by vr8hub** [comment]
For italics, when something in an italicized phrase needs to stand out, then yes, it's unitalicized. IOW, "this is something that _needs_ to be italicized" and "_this is something that_ needs _to be italicized_" accomplish the same goal: "needs" stands out from the rest of the text. And you're right, if that's the "title", then `<q>` is not correct. I guess an unsemanticated italic is the lesser of all evils.

Re the note, I'm not going to argue too hard; this is all subjective, and this is your production, not mine. That means these are my thoughts, not my instructions. :)
I don't think the V, § 19 is that important in our context; in Giles context, that's how he told you where to go to see the comments. If you want to tell them that it's Tu Mu's comments, then "See Tu Mu's comments in note 292" would seem to be sufficient. If you still want to keep everything, then maybe "Cf. Tu Mu's comments on V § 19 in note 292."? I'm not crazy about using "note" twice in such close proximity. But again, subjective and your call. :)

**Comment by irontigran** [comment]
Re: bracketed phrases: what's something "other than a normal aside"? Giles seems to use brackets for editorial asides within quotes, providing dates, and occasionally cross-references.

He also uses parentheses for all the same reasons, except editorial asides; I haven't been able to discern his reasons for using parentheses versus brackets in any particular case.

**Comment by vr8hub** [comment]
Sorry, I had a household project today.

For example, the bracket in note 79 is in the middle of a quote. That's a clear editorial insert, i.e. an editorial interruption of someone else speaking, and brackets are appropriate.
But in note 87, e.g. the `[AD 1461]`, Giles is the one talking, and it's still a bracket. It's like he's interrupting himself. Same thing in note 152 and 743. In those instances, those appear to me to be parenthetical asides by Giles. He's the one speaking, so there are no reason for brackets.

**Comment by irontigran** [comment]
Okay, fixed all these issues:

- Followed all of your CSS recommendations; meant to center the dedication, but it slipped my mind.
- Changed all brackets to parentheses unless they were inside a quote
