### ISSUE TITLE
Unsemanticated italics

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#68]
1. I've mentioned the one at the beginning of the French blockquote in intro-1 elsewhere.
2. There's a stray unsemanticated italic around the I.e. in endnote 54. It should not be there.
3. There's another one in endnote 275, "…_Chʽi_ is active…". I suspect that one should have a language tag on it, judging from what immediately follows.
4. The last one is in note 655, quoting some soldiers ('Standing as we do in peril…'). Per the manual, we generally don't use quotes and italics; since this is quoted, it doesn't need italics.

**Comment by irontigran** [comment]
All but the French blockquote fixed [here](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/aa863121e71a31e0bbd96e0074f3fdf969150720)
