### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#69]
1. There's a typo in intro-1, "The first in in…"; it should be "The first is in…".
2. There's a stray en-dash in endnote 206; "…your opponent–has counted…". It should be an em-dash. Also in that note, in "not will he turn his army back" the "not" should be "nor".
3. In chapter 12, "When fire breaks out inside to enemy's camp", the "to" should be "the".
4. Endnotes 75, 80, 146, 293 needs an ending period. 146 has a comma instead of a period, the others have nothing.
5. Conversely, note 294 has too many. :) The period ending the quote functions as one for the whole sentence. (Same as note 296, e.g.)
6. Endnote 169 has Altoghether instead of Altogether.
7. There are numerous instances of `AD.`, i.e. AD followed by an unnecessary period. I happened on one, and found the others by searching for `AD</abbr>\.`. Same for BC.
8. The second paragraph in endnote 218, "全軍, etc. The more I think about it…" does not appear in either scan, and I can't find it in the PG transcription, either.
9. Note 294 has "“The Tʽu Shu reads 本 an”; there should be comma after the Chinese character.
10. The quote in note 410 that ends "will not cause any trouble" needs a period. There's not one in the scan, either, but there clearly should be one there.
11. Note 442 has "qulaity" instead of "quality".
12. The bracketed phrase at the end of note 558 (Tso Chuan…) has the period outside the closing bracket. Since the sentence prior has a period, the bracketed phrase is self-contained, and the period should be inside the bracket. Same for the one at the end of note 580. The Nota bene in note 584 needs one as well.
13. The period after "Vol I" in note 777 should be a comma.

**Comment by irontigran** [comment]
Most of these should be fixed.

For number 8 - the second paragraph in note 218 is pulled from the 'corrigenda' in the back of the book. After some discussion with Alex, I decided I didn't want to attempt to modify the actual text, so it got appended to the footnote.

**Comment by vr8hub** [comment]
Ahh, right, I remember that discussion now. I don't disagree with not trying to modify the text, but I wonder if we should have some text there, like "From corrigenda" or "From errata" or something.  (I saw the discussion and still didn't realize what it was, so I suspect a reader new to it is going to say, "What!?") But, an idle thought on my part, it's totally up to you.

**Comment by irontigran** [comment]
Yeah, I like the idea. Added the text in [this commit](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/6cba654a20f42e4685f9b7657b9a6952b0237a42)
