### ISSUE TITLE
Quoting Greek

### ISSUE THREAD

**Issue by irontigran** [irontigran/sun-tzu_the-art-of-war_lionel-giles#7]
In the first chapter 11, section 23 footnote, Giles' quotes Thucydides in the original Greek. Going to have to ignore the footnote or figure out how to render Greek.

**Comment by thewchan** [comment]
The Greek should be mostly renderrable in unicode:

‘τό τε ξύμπαν γνῶτε, ὦ ἄνδρες στρατιῶται, ἀναγκαῖόν τε ὂν ὑμῖν ἀνδράσιν ἀγαθοῖς γίγνεσθαι ὡς μὴ ὄντος χωρίου ἐγγὺς ὅποι ἂν μαλακισθέντες σωθείητε

Some of the diacritics might be tricky though, as I believe they are only used for ancient greek. The source of this quote is here:
[http://www.perseus.tufts.edu/hopper/text;jsessionid=8815B4D4EBED468C13B317648270006B?doc=Perseus%3Atext%3A1999.01.0199%3Abook%3D7%3Achapter%3D77%3Asection%3D7](http://www.perseus.tufts.edu/hopper/text;jsessionid=8815B4D4EBED468C13B317648270006B?doc=Perseus%3Atext%3A1999.01.0199%3Abook%3D7%3Achapter%3D77%3Asection%3D7
)

It's English translation is here (see verse[7]):
[http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0105%3Abook%3D7%3Achapter%3D77](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0105%3Abook%3D7%3Achapter%3D77)

**Comment by irontigran** [comment]
Thanks for the link! I ended up copying and pasting the appropriate fragment from your source, which I think gets past me having to look up the appropriate Unicode code points.
