### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#70]
1. Vice versa is italicized in note 243 and should not be. Also, it should just be vice versa in all three places it appears; the circumflex is archaic and unnecessary now.
2. The short verse in note 259 needs to be indented on the first line to match the scan. Also, z3998:poem is for when an entire poem is present; z3998:verse is for partial quotations like this one. (You'll need the CSS as well.)
3. The "Victory" is referred to in note 284; it should be italicized (instead of quotes) and semanticated as a ship.
4. There are a few unsemanticated Col. abbreviations in endnotes: notes 326, 331, and 522.
5. Ditto Gen. in notes 465 and 472. You might check for other untagged abbreviations.
6. The word "nuance" is italicized in notes 350 and 749. It was considered a foreign word at the time; I don't believe either instance is emphasis, and so should not be italicized.
7. Note 672 has a second reference to _Art of War_ that isn't semanticated.

**Comment by irontigran** [comment]
Rereading [section 7.5](https://standardebooks.org/manual/1.1.1/7-high-level-structural-patterns#7.5) of the manual - am I correct in thinking the CSS is the same, I just have to change "z3998:poem" to "z3998:verse"?

**Comment by vr8hub** [comment]
Yes, but I think you have an actual poem in there, too, so you might have to have both. I didn't look closely at the other ones, though.

**Comment by irontigran** [comment]
All issues should be fixed [here](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/d72c6f9a1029154b3384dc0cf70efaa35c3bfba8) and [here](https://github.com/irontigran/sun-tzu_the-art-of-war_lionel-giles/commit/7814220c03a7d4f81f32288b7ccfce25bcb0b8b3)
