### ISSUE TITLE
Final issues

### ISSUE THREAD

**Issue by vr8hub** [irontigran/sun-tzu_the-art-of-war_lionel-giles#71]
1. Typogrify makes a lot of changes that should be accepted, almost all of them surrounding the ellipses added in your recent changes. I didn't check _every_ change, so you should review them, but the vast majority appear to be correct.
2. Semanticate makes a couple of changes that should be made, and as before, several more that should not. The first two (eoc on an abbr, roman tag on "ch. VIII") look correct, the others look like they can be ignored.
3. The addition of the "continued" class a couple of tools versions ago, and the accompanying automatic indenting of paragraphs following a blockquote, list, etc., means that you should give it a review for instances when it should be used. For example, in the first preface (Sun Wu and His Book), the blockquote starting "Military writers look upon Sun Wu…" is followed by "He also says:—". With the changes in 1.6+, that paragraph is indented by default, and thus needs the "continued" class on it to not be indented, which it should not be. A little later in the same preface, there's a "The other is in XI" in the same situation. And so on throughout. The same is true for instances following a list where the paragraph immediately following should not be indented. I mentioned one of these in #67, but there are probably others.
4. The section on deduplicating of paragraph id's still isn't on the website yet, but the text says prepend the id of the closest section. So, e.g., in preface 1, the id is "translators-intro-1", while the id's are "intro-1-p-X". They should be "translators-intro-1-p-X", and the same throughout it and the other files.
5. The verse in note-259 I mentioned in #70 wasn't updated to indent the first line to match the scan. Was that intentional?
6. I did not look for typos, but happened to see this one: in note-169, the "in the chapter" link needs a space after it before the leading paren of "(Therefore…").

**Comment by irontigran** [comment]
> The verse in note-259 I mentioned in #70 wasn't updated to indent the first line to match the scan.

Somewhat intentional - I didn't ascribe any particular meaning to the indentation in the page scans (and the poetry is not a main focus of the book), so I didn't bother trying to match the indentation. I see that the manual provides a standard way to vary indentation between lines, so it's not much effort to match the scans.

Is that a worthwhile goal? I've generally taken the attitude that we're not trying to match the exact formatting of the page scans (with the exception of the dedication, music scores, etc).

**Comment by vr8hub** [comment]
Philosophically, we do generally try match the formatting of poetry, verse, etc. That's why we have the standard poetry/verse/song CSS, so that we _can_ match the formatting. And we try to match that formatting even in books where poetry isn't the emphasis; unlike prose, the formatting of poetry in print is usually intentional, so we respect that (within reason). It's a judgment call sometimes whether a line should be indented i1 or i2, e.g., but we try to match the overall look.
